"""initial schema

Revision ID: 49d4d2db88cd
Revises: 
Create Date: 2026-06-28 18:42:45.590582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d4d2db88cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mesa')),
    sa.UniqueConstraint('numero', name=op.f('uq_mesa_numero'))
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('disponible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producto'))
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol')),
    sa.UniqueConstraint('nombre', name=op.f('uq_rol_nombre'))
    )
    op.create_table('suministro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suministro'))
    )
    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suministro_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida', 'ajuste', name='tipomovimiento', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.String(length=60), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['suministro_id'], ['suministro.id'], name=op.f('fk_movimiento_inventario_suministro_id_suministro'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento_inventario'))
    )
    op.create_index(op.f('ix_movimiento_inventario_suministro_id'), 'movimiento_inventario', ['suministro_id'], unique=False)
    op.create_table('receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('suministro_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_receta_producto_id_producto'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['suministro_id'], ['suministro.id'], name=op.f('fk_receta_suministro_id_suministro'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receta')),
    sa.UniqueConstraint('producto_id', 'suministro_id', name=op.f('uq_receta_producto_id'))
    )
    op.create_index(op.f('ix_receta_producto_id'), 'receta', ['producto_id'], unique=False)
    op.create_index(op.f('ix_receta_suministro_id'), 'receta', ['suministro_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_usuario_rol_id_rol'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('correo', name=op.f('uq_usuario_correo'))
    )
    op.create_index(op.f('ix_usuario_rol_id'), 'usuario', ['rol_id'], unique=False)
    op.create_table('compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cajero_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=120), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comprado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cajero_id'], ['usuario.id'], name=op.f('fk_compra_cajero_id_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compra'))
    )
    op.create_index(op.f('ix_compra_cajero_id'), 'compra', ['cajero_id'], unique=False)
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('mesero_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('en_mesa', 'para_llevar', name='tipocuenta', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('estado', sa.Enum('abierta', 'por_cobrar', 'pagada', 'cancelada', name='estadocuenta', native_enum=False, create_constraint=True), server_default=sa.text("'abierta'"), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('abierta_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('cerrada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], name=op.f('fk_cuenta_mesa_id_mesa'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mesero_id'], ['usuario.id'], name=op.f('fk_cuenta_mesero_id_usuario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cuenta'))
    )
    op.create_index(op.f('ix_cuenta_mesa_id'), 'cuenta', ['mesa_id'], unique=False)
    op.create_index(op.f('ix_cuenta_mesero_id'), 'cuenta', ['mesero_id'], unique=False)
    op.create_table('detalle_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('suministro_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compra.id'], name=op.f('fk_detalle_compra_compra_id_compra'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['suministro_id'], ['suministro.id'], name=op.f('fk_detalle_compra_suministro_id_suministro'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_compra'))
    )
    op.create_index(op.f('ix_detalle_compra_compra_id'), 'detalle_compra', ['compra_id'], unique=False)
    op.create_index(op.f('ix_detalle_compra_suministro_id'), 'detalle_compra', ['suministro_id'], unique=False)
    op.create_table('detalle_cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_preparacion', 'listo', 'entregado', 'cancelado', name='estadococina', native_enum=False, create_constraint=True), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], name=op.f('fk_detalle_cuenta_cuenta_id_cuenta'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], name=op.f('fk_detalle_cuenta_producto_id_producto'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_cuenta'))
    )
    op.create_index(op.f('ix_detalle_cuenta_cuenta_id'), 'detalle_cuenta', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_detalle_cuenta_producto_id'), 'detalle_cuenta', ['producto_id'], unique=False)
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('cajero_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'tarjeta', 'transferencia', 'otro', name='metodopago', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pagado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cajero_id'], ['usuario.id'], name=op.f('fk_pago_cajero_id_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], name=op.f('fk_pago_cuenta_id_cuenta'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pago'))
    )
    op.create_index(op.f('ix_pago_cajero_id'), 'pago', ['cajero_id'], unique=False)
    op.create_index(op.f('ix_pago_cuenta_id'), 'pago', ['cuenta_id'], unique=False)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('emitido_en', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], name=op.f('fk_ticket_cuenta_id_cuenta'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket')),
    sa.UniqueConstraint('cuenta_id', name=op.f('uq_ticket_cuenta_id')),
    sa.UniqueConstraint('folio', name=op.f('uq_ticket_folio'))
    )
    op.create_index(op.f('ix_ticket_cuenta_id'), 'ticket', ['cuenta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_cuenta_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_pago_cuenta_id'), table_name='pago')
    op.drop_index(op.f('ix_pago_cajero_id'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_detalle_cuenta_producto_id'), table_name='detalle_cuenta')
    op.drop_index(op.f('ix_detalle_cuenta_cuenta_id'), table_name='detalle_cuenta')
    op.drop_table('detalle_cuenta')
    op.drop_index(op.f('ix_detalle_compra_suministro_id'), table_name='detalle_compra')
    op.drop_index(op.f('ix_detalle_compra_compra_id'), table_name='detalle_compra')
    op.drop_table('detalle_compra')
    op.drop_index(op.f('ix_cuenta_mesero_id'), table_name='cuenta')
    op.drop_index(op.f('ix_cuenta_mesa_id'), table_name='cuenta')
    op.drop_table('cuenta')
    op.drop_index(op.f('ix_compra_cajero_id'), table_name='compra')
    op.drop_table('compra')
    op.drop_index(op.f('ix_usuario_rol_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_receta_suministro_id'), table_name='receta')
    op.drop_index(op.f('ix_receta_producto_id'), table_name='receta')
    op.drop_table('receta')
    op.drop_index(op.f('ix_movimiento_inventario_suministro_id'), table_name='movimiento_inventario')
    op.drop_table('movimiento_inventario')
    op.drop_table('suministro')
    op.drop_table('rol')
    op.drop_table('producto')
    op.drop_table('mesa')
    # ### end Alembic commands ###
